### PR TITLE
env largemodel test 2

### PR DESCRIPTION
**Pull request by wanliAlex**
another solution to change the largemodel test environment.

### CODE REVIEW

**Comment by pandu-k** [comment]
purpose of this test: 
- So on unit tests we don't have as many guarantees regarding the environment
- This means the normal unit test environment isn't the most appropriate test out ONNX models
- The solution is this special unit test environment that sets up the environments so that ONNX models can be used

Questions:
- how come the tests don't fail in existing environments?
- To confirm, this is a CPU tests
- How come there are no new tests? Answer: these are unit tests defined in the Marqo repo, not API tests

Feedback:
- More clear documentation/description of the problem and how this is solving it

**Comment by pandu-k** [comment]
More questions:

- what the test is for? 
- why is it needed? 
- what machines it’s designed to work on?
- What if it runs on a CUDA enabled instances? 
- What if runs on a CPU only instance?

**Comment by wanliAlex** [comment]
> purpose of this test:
> 
> * So on unit tests we don't have as many guarantees regarding the environment
> * This means the normal unit test environment isn't the most appropriate test out ONNX models
> * The solution is this special unit test environment that sets up the environments so that ONNX models can be used
> 
> Questions:
> 
> * how come the tests don't fail in existing environments?
> * To confirm, this is a CPU tests
> * How come there are no new tests? Answer: these are unit tests defined in the Marqo repo, not API tests
> 
> Feedback:
> 
> * More clear documentation/description of the problem and how this is solving it

1. We choose the auto fallback feature in onnxruntime. So even if the cuda is not supported with the given device `cuda`, it will just throw a warning and run on `cpu`.
2. The updated environment will be use for largemodel test with cuda
3. This is just to change the test environment for largemodel unittests. Check [here](https://github.com/marqo-ai/marqo/blob/2b8f7023debcc65a64339ecdccfca7285f3efc17/.github/workflows/largemodel_unit_test_CI.yml#L95-L96)

**Review by pandu-k — CHANGES_REQUESTED** [review]
more documentation needed - see comments

**Comment by pandu-k** [comment]
> > purpose of this test:
> > 
> > * So on unit tests we don't have as many guarantees regarding the environment
> > * This means the normal unit test environment isn't the most appropriate test out ONNX models
> > * The solution is this special unit test environment that sets up the environments so that ONNX models can be used
> > 
> > Questions:
> > 
> > * how come the tests don't fail in existing environments?
> > * To confirm, this is a CPU tests
> > * How come there are no new tests? Answer: these are unit tests defined in the Marqo repo, not API tests
> > 
> > Feedback:
> > 
> > * More clear documentation/description of the problem and how this is solving it
> 
> 1. We choose the auto fallback feature in onnxruntime. So even if the cuda is not supported with the given device `cuda`, it will just throw a warning and run on `cpu`.
> 2. The updated environment will be use for largemodel test with cuda
> 3. This is just to change the test environment for largemodel unittests. Check [here](https://github.com/marqo-ai/marqo/blob/2b8f7023debcc65a64339ecdccfca7285f3efc17/.github/workflows/largemodel_unit_test_CI.yml#L95-L96)

Thanks Li.
1. Can you make it super clear, in comments on the tox file about this. 
2. Does this require an update to github workflow in the Marqo repo too? If so please link the associated PR 
3. Is it possible to detect the warning and throw an error if CPU rather than CUDA is used? This may mean adding extra logic to the Marqo test repo

**Comment by wanliAlex** [comment]
This pull request aims to modify the unittest environment for large models. Currently, the [unittest environment relies](https://github.com/marqo-ai/marqo/blob/2b8f7023debcc65a64339ecdccfca7285f3efc17/.github/workflows/largemodel_unit_test_CI.yml#L93-L96) on the tox environment, which builds the environment based on the requirements.txt file. However, this approach has a problem: the largemodel test runs on a cuda instance, and we want to test how different models, specifically onnx models, perform on this device. The requirements.txt file includes the package onnxruntime, but to test onnx models on a cuda device, we need the onnxruntime-gpu package instead.

Therefore, this PR proposes replacing the onnxruntime package with onnxruntime-gpu in the largemodel unittest environment to enable testing onnx models on a cuda device.

Note: although this is a PR on the api-test-repo, it does not include any tests but only affect the largemodel unittest CI Pipelines.

**Comment by pandu-k** [comment]
> This pull request aims to modify the unittest environment for large models. Currently, the [unittest environment relies](https://github.com/marqo-ai/marqo/blob/2b8f7023debcc65a64339ecdccfca7285f3efc17/.github/workflows/largemodel_unit_test_CI.yml#L93-L96) on the tox environment, which builds the environment based on the requirements.txt file. However, this approach has a problem: the largemodel test runs on a cuda instance, and we want to test how different models, specifically onnx models, perform on this device. The requirements.txt file includes the package onnxruntime, but to test onnx models on a cuda device, we need the onnxruntime-gpu package instead.
> 
> Therefore, this PR proposes replacing the onnxruntime package with onnxruntime-gpu in the largemodel unittest environment to enable testing onnx models on a cuda device.
> 
> Note: although this is a PR on the api-test-repo, it does not include any tests but only affect the largemodel unittest CI Pipelines.

Can you please make relevant documentation a part of the code (via comments or README update)

**Pull request closed without merging**
